#! /usr/bin/env fish

################################################################################
###                               swayimg-hyprland                           ###
################################################################################
# Replicate the overlay behavior of swayimg, but in hyprland                   #
#                                                                              #
# Because hyprland can't just have a window tree, like swaymsg -t get_tree, or #
# even use absolute and relative coordinates consistently, or even provide     #
# half decent documentation of the protocols/commands, this took way longer    #
# than it should have and I'm salty
################################################################################
#                                Hari Ganti | 2025/03/11 | hariganti@gmail.com #
################################################################################

# Check for appropriate args
if test (count $argv) -ne 1
  echo 'Usage is "swayimg-hyprland <path/to/image>"'
  exit
end

# Get window parameters (absolute coordinates)
set -l window \
  (
    hyprctl clients -j \
      | jq -r '.[]
        | select(.focusHistoryID == 0)
        | .at.[0], .at.[1], .size.[0], .size.[1], .monitor'
#            x        y       width     height     monitor
  )

# Get monitor properties
set -l monitor \
  (
    hyprctl monitors -j \
      | jq -r ".[]
        | select(.id == $window[5])
        | .x, .y"
  )

# Adjust size and position
set -l size $window[3..4]
set -l pos \
  (math $window[1] - $monitor[1]) \
  (math $window[2] - $monitor[2]) \

# Uses relative coordinates (...) and quotes for the rule (no documentation...)
hyprctl dispatch exec "[move $pos; size $size]" swayimg $argv[1]
